filter_kgraph_std_dev
NCATSTranslator/OperationsAndWorkflows pull request #30
Opened 2021-06-08 19:37 UTC by finnagin

2021-06-08 19:38 UTC, finnagin commented
FYI: input/output json still needs to be made and documentation generated etc. 

Currently this is just a rough draft for the yaml file.

2021-06-18 16:14 UTC, dkoslicki commented
@finnagin is this ready for review?

2021-06-18 19:30 UTC, finnagin commented
@dkoslicki I believe this, PR #31 , and PR #32 are all ready for review.

2021-06-21 20:43 UTC, patrickkwang requested changes
Looks good! Minor suggestions.

2021-06-21 20:43 UTC, patrickkwang commented on operations/filter_kgraph_std_dev.yml
> +      description: This indicates if you only want to filter on specific edge_keys. If not provided or empty all edges will be filtered on and edge_key will not be considered when filtering.
```suggestion
      description: This indicates if you only want to filter on specific edge_keys. If not provided or empty, all edges will be filtered on.
```

2021-06-21 20:43 UTC, patrickkwang commented on operations/filter_kgraph_std_dev.yml
> +      description: This indicates if you only want nodes corresponding to a specific list of qnode_keys to be removed. If not provided oe empty no nodes will be removed when filtering.
```suggestion
      description: This indicates if you only want nodes corresponding to a specific list of qnode_keys to be removed. If not provided or empty, no nodes will be removed when filtering.
```

2021-06-23 03:42 UTC, dkoslicki approved these changes

2021-06-29 20:03 UTC, patrickkwang approved these changes

2021-06-29 20:08 UTC, merged