Filter kgraph percentile
NCATSTranslator/OperationsAndWorkflows pull request #32
Opened 2021-06-15 18:47 UTC by finnagin

2021-06-28 17:22 UTC, dkoslicki approved these changes

2021-06-29 20:38 UTC, patrickkwang requested changes

2021-06-29 20:38 UTC, patrickkwang commented on operations/filter_kgraph_percentile.yml
> +      description: This indicates if you only want to filter on specific edge_keys. If not provided or empty all edges will be filtered on and edge_key will not be considered when filtering.
```suggestion
      description: This indicates if you only want to filter on specific edge_keys. If not provided or empty, all edges will be filtered on.
```

2021-06-29 20:38 UTC, patrickkwang commented on operations/filter_kgraph_percentile.yml
> +      description: This indicates if you only want nodes corresponding to a specific list of qnode_keys to be removed. If not provided oe empty no nodes will be removed when filtering.
```suggestion
      description: This indicates if you only want nodes corresponding to a specific list of qnode_keys to be removed. If not provided or empty, no nodes will be removed when filtering.
```

2021-06-29 20:38 UTC, patrickkwang commented on operations/filter_kgraph_percentile.yml
> +      description: Indictes whether to remove above or below the given threshold.
```suggestion
      description: Indicates whether to remove above or below the given threshold.
```

2021-06-29 20:38 UTC, dkoslicki requested changes

2021-06-29 20:38 UTC, dkoslicki commented on docs/filter_kgraph_percentile.md
> +  remove_above:
`keep_above_or_below` with the options of `above` or `below` @finnagin

2021-06-29 20:41 UTC, dkoslicki requested changes

2021-06-29 20:41 UTC, dkoslicki commented on docs/filter_kgraph_percentile.md
> +  edge_keys:
`qedge_keys`

2021-06-29 20:48 UTC, dkoslicki requested changes
Also applicable to all filters: remove all results that have bindings to edges/nodes filtered

2021-06-29 20:48 UTC, dkoslicki commented on docs/filter_kgraph_percentile.md
> +      removed when filtering.
Add the following: Allows you to choose what happens to source and target nodes attached to edges that get filtered out. Only applicable to qnodes that are either sources or targets of edges with the provided `edge_attribute`.

2021-07-14 15:49 UTC, dkoslicki approved these changes

2021-07-20 19:02 UTC, patrickkwang requested changes

2021-07-20 19:07 UTC, cbizon approved these changes

2021-07-20 19:10 UTC, patrickkwang approved these changes

2021-07-20 19:54 UTC, merged