Add lookup operation
NCATSTranslator/OperationsAndWorkflows pull request #34
Opened 2021-06-22 16:52 UTC by patrickkwang

2021-06-23 03:28 UTC, edeutsch approved these changes

2021-06-23 03:45 UTC, dkoslicki requested changes
Not clear how this differs from `fill`. Mind clarifying?

2021-06-23 12:55 UTC, patrickkwang commented
Fill only adds to the knowledge graph. Lookup is fill + bind + complete_results.

2021-06-23 21:34 UTC, finnagin approved these changes

2021-06-29 20:55 UTC, dkoslicki requested changes

2021-06-29 20:55 UTC, dkoslicki commented on docs/lookup.md
> +This operation adds knodes/kedges and (complete) results. Implementations of this operation are _unique_; their behavior is not fully-specified by the operation parameters.
Can we add an indication that this is combo operation of `fill+bind+complete` results?

2021-07-02 04:24 UTC, dkoslicki approved these changes

2021-07-02 04:25 UTC, merged