answer coalesce via enrichment
NCATSTranslator/OperationsAndWorkflows pull request #45
Opened 2021-07-27 02:43 UTC by cbizon

An operation for creating new results by combining input results via enrichment analyses.

2021-07-27 18:11 UTC, patrickkwang requested changes
Makes sense! Minor suggestions.

2021-07-27 18:11 UTC, patrickkwang commented on operations/enrich_results.yml
> +- add qnodes
```suggestion
- add qedges
```

2021-07-27 18:11 UTC, patrickkwang commented on operations/enrich_results.yml
> +- add kedges
```suggestion
- add knodes
```

2021-07-27 18:11 UTC, patrickkwang commented on operations/enrich_results.yml
> +      default: []
```suggestion
```
IMO the default `[]` here is counter-intuitive. The description implies what happens when this key is left out, so I don't think we need a default. We could even go as far as to insist that the array be non-empty with `minLength: 1`.

2021-07-27 20:15 UTC, dkoslicki requested changes

2021-07-27 20:15 UTC, dkoslicki commented on docs/enrich_results.md
> +    type: float
type: number?

2021-07-27 20:15 UTC, dkoslicki commented on docs/enrich_results.md
> +    type: array
item types?

2021-07-27 20:20 UTC, cbizon commented on docs/enrich_results.md
> +    type: float
Changed to float

2021-07-27 20:21 UTC, cbizon commented on docs/enrich_results.md
> +    type: array
added item type strings

2021-07-27 20:43 UTC, patrickkwang approved these changes

2021-07-27 21:00 UTC, dkoslicki commented
@cbizon I think the YAML was changed, but the docs/markdown files haven't been recompiled

2021-08-03 20:10 UTC, dkoslicki approved these changes

2021-08-03 20:10 UTC, merged